# Hyperparameters
model:
  gamma: 0.99  # Discount factor
  epsilon: 1.0  # Exploration rate
  epsilon_min: 0.1
  epsilon_decay: 0.995
  batch_size: 64
  memory_size: 10000
  update_target_freq: 10  # Frequency to update the target network
env:
  height: 100
  width: 100
  num_destinations: 10
train:
  num_episodes: 1000
  max_steps: 1000
  render: False
  log_freq: 10
  save_freq: 100
  save_dir: models
  load_model: False
  load_path: models/model.pt
optimizer: 
  fn: adamw
  kwargs:
    lr: 0.001
    momentum: 0.9
    beta1: 0.9
    beta2: 0.999
criterion: mse
wandb:
  kwargs:
    mode: disabled
    project: dqn
    entity: null
    group: null